name: PR Security Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Checkout private action repo
        uses: actions/checkout@v4
        with:
          repository: vsin-123/DevSecOpsAI_PR_Guard
          token: ${{ secrets.GH_PAT }}
          path: DevSecOpsAI_PR_Guard

      - name: AI PR Review
        uses: ./DevSecOpsAI_PR_Guard
        with:
          ai-key: ${{ secrets.GEMINI_API_KEY }}
          provider: gemini
          #model: gemini-1.5-flash  # Optional: default gpt-4o-mini
          max-files: 20             # Optional: default 20
          mode: devsecops           # Optional: default devsecops
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
